# -*- coding: utf-8 -*-
"""pneumonia_clssification_cnn_transfer_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AOsPPr-BJ-jS3pXQ0d10tVeXUaQxUsRQ

# **Introduction**
*Classification of chest X-ray images to detect pneumonia.*

The dataset used in this analysis contains a large number of chest X-ray images categorized as either 'NORMAL' or 'PNEUMONIA'.

Due to the limited size of the dataset and the need to improve the model's ability to generalize to unseen data, data augmentation techniques were employed. These techniques help to artificially increase the diversity of the training set by applying transformations such as rotations, zooms, and flips to the existing images.

The Project contain three different model architectures:

1.  **Sequential Model:** An initial sequential CNN model was developed. However, this model exhibited bias in its predictions, likely due to imbalances within the dataset.

2.  **Transfer Learning with DenseNet121:** Transfer learning was then applied using the DenseNet121 pre-trained model. While transfer learning generally improves performance, this specific model also did not achieve satisfactory results, possibly still influenced by biases in the data.

3.  **Transfer Learning with VGG16:** Finally, transfer learning with the VGG16 pre-trained model was implemented. This approach yielded the most promising results, demonstrating improved accuracy and a better balance in predictions across the two classes.

The subsequent sections of this notebook detail the data loading, preprocessing, model building, training, evaluation, and visualization steps involved in this pneumonia classification task.

# **Import Libraries**
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

"""**List Directories**"""

# List the folders present in chest_xray
os.listdir("/kaggle/input/chest-xray-pneumonia/chest_xray")

"""**Count Training Pneumonia Images**"""

# Count the number of pneumonia images in the training dataset.
len(os.listdir("/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA"))

"""**Define Data Directories**"""

# Define directories for train, test, and validation sets.
train_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/train"
test_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/test"
val_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/val"

"""**Summarize Dataset Statistics**"""

# Count and print the number of pneumonia and normal images in each dataset.
print("Train set:\n========================================")
print(f"PNEUMONIA={len(os.listdir(os.path.join(train_dir, 'PNEUMONIA')))}")
print(f"NORMAL={len(os.listdir(os.path.join(train_dir, 'NORMAL')))}")

print("Test set:\n========================================")
print(f"PNEUMONIA={len(os.listdir(os.path.join(test_dir, 'PNEUMONIA')))}")
print(f"NORMAL={len(os.listdir(os.path.join(test_dir, 'NORMAL')))}")

print("Validation set:\n========================================")
print(f"PNEUMONIA={len(os.listdir(os.path.join(val_dir, 'PNEUMONIA')))}")
print(f"NORMAL={len(os.listdir(os.path.join(val_dir, 'NORMAL')))}")

"""**Visualize Sample Pneumonia Images**"""

#visualizes 9 images from the pneumonia class in the training set.
pneumonia = os.listdir("/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA")
pneumonia_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/train/PNEUMONIA"

plt.figure(figsize=(20, 10))

for i in range(3):
    plt.subplot(1, 3, i + 1)
    img = plt.imread(os.path.join(pneumonia_dir, pneumonia[i]))
    plt.imshow(img, cmap='gray')
    plt.axis('off')

plt.tight_layout()

"""**Visualize Sample Normal Images**"""

#Visualize 9 images from the normal class in train set.
normal = os.listdir("/kaggle/input/chest-xray-pneumonia/chest_xray/train/NORMAL")
normal_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/train/NORMAL"

plt.figure(figsize=(20, 10))

for i in range(3):
    plt.subplot(1, 3, i + 1)
    img = plt.imread(os.path.join(normal_dir, normal[i]))
    plt.imshow(img, cmap='gray')
    plt.axis('off')

plt.tight_layout()

"""**Data Augmentation Configuration**"""

# from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import ImageDataGenerator

image_generator = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    # centers the data around zero
    samplewise_center=True,
    # standardizes the scale across all images
    samplewise_std_normalization=True
)

"""**Create Data Generators**"""

# Divides the images into batches , and applies the augmentations and normalization.
train = image_generator.flow_from_directory(train_dir,
                                            batch_size=8,
                                            shuffle=True,
                                            class_mode='binary',
                                            target_size=(180, 180))

validation = image_generator.flow_from_directory(val_dir,
                                                batch_size=1,
                                                shuffle=False,
                                                class_mode='binary',
                                                target_size=(180, 180))

test = image_generator.flow_from_directory(test_dir,
                                            batch_size=1,
                                            shuffle=False,
                                            class_mode='binary',
                                            target_size=(180, 180))

"""**Check Class Imblance**"""

# Class weights
# Will actually the class imblance.
num_pneumonia = len(os.listdir(os.path.join(train_dir, 'PNEUMONIA')))
num_normal = len(os.listdir(os.path.join(train_dir, 'NORMAL')))

weight_for_0 = num_pneumonia / (num_normal + num_pneumonia)
weight_for_1 = num_normal / (num_normal + num_pneumonia)

class_weight = {0: weight_for_0, 1: weight_for_1}

print(f"Weight for class 0: {weight_for_0:.2f}")
print(f"Weight for class 1: {weight_for_1:.2f}")

"""# **Define Sequential Model Architecture**"""

import os
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D, Dropout, Flatten, BatchNormalization
from keras.callbacks import ModelCheckpoint  # Import ModelCheckpoint
from tensorflow.keras.regularizers import l2
from tensorflow.keras.layers import MaxPooling2D

weight_for_0 = num_normal / (num_normal + num_pneumonia)
weight_for_1 = num_pneumonia / (num_normal + num_pneumonia)

class_weight = {0: weight_for_0, 1: weight_for_1}

print(f"Weight for class 0: {weight_for_0:.2f}")
print(f"Weight for class 1: {weight_for_1:.2f}")


model = Sequential()

# Initial Convolutional Block
model.add(Conv2D(32, (3, 3), input_shape=(180, 180, 3), activation='relu', padding='same',
                 kernel_regularizer=l2(0.001)))  # L2 regularization
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.2))

# Second Convolutional Block
model.add(Conv2D(64, (3, 3), activation='relu', padding='same',
                 kernel_regularizer=l2(0.001)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.2))

# Third Convolutional Block
model.add(Conv2D(128, (3, 3), activation='relu', padding='same',
                 kernel_regularizer=l2(0.001)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.3))  # Increased dropout

# Fourth Convolutional Block
model.add(Conv2D(256, (3, 3), activation='relu', padding='same',
                 kernel_regularizer=l2(0.001)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.3))

# Flatten the feature maps
model.add(Flatten())

# Fully Connected Layers
model.add(Dense(256, activation='relu', kernel_regularizer=l2(0.001)))  # Increased units, L2
model.add(BatchNormalization())
model.add(Dropout(0.5))  # Increased dropout

model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

# Optimizer with a lower learning rate and decay
optimizer = keras.optimizers.Adam(learning_rate=1e-4)

#Compile Sequential Model
model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

model.summary()

# Define the ModelCheckpoint callback
checkpoint_filepath = 'best_model.keras'
model_checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_best_only=True,
    monitor='val_loss',
    mode='min',
    verbose=1
)

"""**Train Sequential Model**"""

r = model.fit(
    train,
    epochs=10,
    validation_data=validation,
    class_weight=class_weight,  # Use the calculated class weights here
    steps_per_epoch=100,
    validation_steps=25,
    callbacks=[model_checkpoint_callback]
)

"""**Evaluate Model Performance**"""

evaluation = model.evaluate(test)
print(f"Test Accuracy: {evaluation[1] * 100:.2f}%")

evaluation = model.evaluate(train)
print(f"Train Accuracy: {evaluation[1] * 100:.2f}%")

"""**Generate Confusion Matrix and Classification Report**"""

from sklearn.metrics import confusion_matrix, classification_report

pred = model.predict(test)

print(confusion_matrix(test.classes, pred > 0.5))
pd.DataFrame(classification_report(test.classes, pred > 0.5, output_dict=True))

"""**Visualize Evaluations**

# **Visualize True vs. False Predictions of Trained Sequential Model**
"""

import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import random
import matplotlib.pyplot as plt

test_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/test"
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(180, 180),
    batch_size=1,
    class_mode='binary',
    shuffle=False
)
model = keras.models.load_model("/kaggle/input/best_model/keras/default/1/best_model.keras")
filenames = test_generator.filenames
class_labels = {v: k for k, v in test_generator.class_indices.items()}
num_images = len(filenames)
random_indices = random.sample(range(num_images), min(8, num_images))  # Changed to 8
fig, axes = plt.subplots(2, 4, figsize=(16, 8))  # Changed to 2x4 grid
print("\nPredictions for 8 Random Images:")

predictions = []  # List to store prediction results (True/False)
for i, ax in zip(random_indices, axes.flatten()):
    img_path = os.path.join(test_dir, filenames[i])
    img = keras.preprocessing.image.load_img(img_path, target_size=(180, 180))
    img_array = keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    pred = model.predict(img_array, verbose=0)[0][0]
    predicted_label = "PNEUMONIA" if pred > 0.5 else "NORMAL"
    original_class_index = test_generator.classes[i]
    original_label = class_labels[original_class_index]
    ax.imshow(img)
    ax.set_title(f"Pred: {predicted_label} ({pred:.2f})\nActual: {original_label}", fontsize=8)
    ax.axis('off')

    # Store prediction result
    predictions.append(predicted_label == original_label)

plt.tight_layout()
plt.show()

# --- Visualization of True vs. False Predictions ---
true_count = sum(predictions)
false_count = len(predictions) - true_count

plt.figure(figsize=(6, 6))
plt.bar(['True', 'False'], [true_count, false_count], color=['green', 'red'])
plt.ylabel('Number of Predictions')
plt.title('True vs. False Predictions (8 Random Images)')
plt.show()

"""# **Transfer learning**

# **DenseNet121 model (without its original classification layer):**

**Import libraries and Initialize DenseNet121 as base model**
"""

from keras.applications.densenet import DenseNet121
from keras.layers import Dense, GlobalAveragePooling2D
from keras.models import Model
from keras import backend as K

base_model = DenseNet121(input_shape=(180, 180, 3), include_top=False, weights='imagenet', pooling='avg')

base_model.summary()

"""**Model's no of Layers**"""

layers = base_model.layers
print(f"The model has {len(layers)} layers")

"""**Define Model Architecture**"""

#model = Sequential()
base_model = DenseNet121(include_top=False, weights='imagenet')
x = base_model.output

x = GlobalAveragePooling2D()(x)

predictions = Dense(1, activation="sigmoid")(x)

model = Model(inputs=base_model.input, outputs=predictions)

"""**Diclare Callback to save best model**"""

from keras.callbacks import ModelCheckpoint
checkpoint_filepath = 'best_chest_xray_model.keras'
model_checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_best_only=True,
    monitor='val_accuracy',
    mode='max',
    verbose=1
)

"""**Compile the SFT model**"""

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

"""**Train DenseNet121 model with new data**"""

r = model.fit(
    train,
    epochs=10,
    validation_data=validation,
    class_weight=class_weight,
    steps_per_epoch=100,
    validation_steps=25,
    callbacks=[model_checkpoint_callback]
)

"""**Evaluate Model Performance**"""

evaluation = model.evaluate(test)
print(f"Test Accuracy: {evaluation[1] * 100:.2f}%")

evaluation = model.evaluate(train)
print(f"Train Accuracy: {evaluation[1] * 100:.2f}%")

"""**Generate Confusion Matrix and Classification Report**"""

from sklearn.metrics import confusion_matrix, classification_report
predicted_vals = model.predict(test, steps=len(test))

print(confusion_matrix(test.classes, predicted_vals > 0.5))
pd.DataFrame(classification_report(test.classes, predicted_vals > 0.5, output_dict=True))

"""**Visualize Evolution of Supervised Fine Tune DenseNet121 Model**

# **Visualize True vs. False Predictions of SFT DenseNet121 Model**
"""

import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import random
import matplotlib.pyplot as plt

test_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/test"
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(180, 180),
    batch_size=1,
    class_mode='binary',
    shuffle=False
)
model = keras.models.load_model("/kaggle/input/best_densenet121_model/keras/default/1/best_chest_xray_model.keras")
filenames = test_generator.filenames
class_labels = {v: k for k, v in test_generator.class_indices.items()}
num_images = len(filenames)
random_indices = random.sample(range(num_images), min(8, num_images))  # Changed to 8
fig, axes = plt.subplots(2, 4, figsize=(16, 8))  # Changed to 2x4 grid
print("\nPredictions for 8 Random Images:")

predictions = []  # List to store prediction results (True/False)
for i, ax in zip(random_indices, axes.flatten()):
    img_path = os.path.join(test_dir, filenames[i])
    img = keras.preprocessing.image.load_img(img_path, target_size=(180, 180))
    img_array = keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    pred = model.predict(img_array, verbose=0)[0][0]
    predicted_label = "PNEUMONIA" if pred > 0.5 else "NORMAL"
    original_class_index = test_generator.classes[i]
    original_label = class_labels[original_class_index]
    ax.imshow(img)
    ax.set_title(f"Pred: {predicted_label} ({pred:.2f})\nActual: {original_label}", fontsize=8)
    ax.axis('off')

    # Store prediction result
    predictions.append(predicted_label == original_label)

plt.tight_layout()
plt.show()

# --- Visualization of True vs. False Predictions ---
true_count = sum(predictions)
false_count = len(predictions) - true_count

plt.figure(figsize=(6, 6))
plt.bar(['True', 'False'], [true_count, false_count], color=['green', 'red'])
plt.ylabel('Number of Predictions')
plt.title('True vs. False Predictions (8 Random Images)')
plt.show()

"""# VGG16-Model-based Transfer Learning

**Import Libraries and define Directoris**
"""

import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, BatchNormalization, Dropout
from tensorflow.keras.applications import VGG16
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.preprocessing.image import ImageDataGenerator  # Import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix  # Import metrics

# Define your data directories (adjust these paths!)
train_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/train"  # Replace with your training data directory
val_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/val"      # Replace with your validation data directory
test_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/test"    # Replace with your test data directory

"""**Data Augmentation Configuration + Create Data Generators**"""

# Image Data Generators with augmentation (you can adjust these)
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

test_datagen = ImageDataGenerator(rescale=1./255)  # Only rescale for test/val

train = train_datagen.flow_from_directory(
    train_dir,
    target_size=(180, 180),
    batch_size=32,
    class_mode='binary'
)

validation = test_datagen.flow_from_directory(
    val_dir,
    target_size=(180, 180),
    batch_size=16,
    class_mode='binary',
    shuffle=False
)

test = test_datagen.flow_from_directory(
    test_dir,
    target_size=(180, 180),
    batch_size=16,
    class_mode='binary',
    shuffle=False
)

"""**Check Class Weight Imblance**"""

# Class weights (IMPORTANT: Calculate from training data)
pneumonia_count = len(os.listdir(os.path.join(train_dir, 'PNEUMONIA')))
normal_count = len(os.listdir(os.path.join(train_dir, 'NORMAL')))
total_count = pneumonia_count + normal_count

class_weight = {0: (1 / normal_count) * (total_count) / 2.0,
                1: (1 / pneumonia_count) * (total_count) / 2.0}

print("Class Weights:", class_weight)

"""**Load VGG16 base Model and build Architecture**"""

# Load the VGG16 base model
vgg16_base_model = VGG16(input_shape=(180, 180, 3), include_top=False, weights='imagenet')
vgg16_base_model.trainable = False  # Freeze the base model

# Create the model
vgg16_model = Sequential([
    vgg16_base_model,
    GlobalAveragePooling2D(),
    Dense(512, activation='relu'),
    BatchNormalization(),
    Dropout(0.5),  # Reduced dropout slightly
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

"""**Compile Model and Declere Model Checkpoint callback**"""

# Compile the model
opt = Adam(learning_rate=0.00005)  # Even lower learning rate
METRICS = ['accuracy', tf.keras.metrics.Precision(name='precision'), tf.keras.metrics.Recall(name='recall')]
vgg16_model.compile(optimizer=opt, loss='binary_crossentropy', metrics=METRICS)

# ModelCheckpoint callback
checkpoint = ModelCheckpoint(
    'best_vgg16_model.h5',
    monitor='val_accuracy',
    verbose=1,
    save_best_only=True,
    mode='max'
)

"""**Fine Tune VGG16 Model with new tain images**"""

# Train the model
r = vgg16_model.fit(
    train,
    epochs=10,  # You can adjust this
    validation_data=validation,
    class_weight=class_weight,
    steps_per_epoch=100,  # Or len(train) if you want to process the whole training set
    validation_steps=25,   # Or len(validation)
    callbacks=[checkpoint]
)

"""**Evaluate SFT VGG16 Model**"""

evaluation = model.evaluate(test)
print(f"Test Accuracy: {evaluation[1] * 100:.2f}%")

evaluation = model.evaluate(train)
print(f"Train Accuracy: {evaluation[1] * 100:.2f}%")

"""**Generate Confusion Matrix and Classification Report**"""

predicted_vals = model.predict(test, steps=len(test))

print(confusion_matrix(test.classes, predicted_vals > 0.5))
pd.DataFrame(classification_report(test.classes, predicted_vals > 0.5, output_dict=True))

"""**Visualization Evaluation of SFT VGG16 Model **

# **Visualize True vs. False Predictions of SFT Vgg16 Model**
"""

import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import random
import matplotlib.pyplot as plt

test_dir = "/kaggle/input/chest-xray-pneumonia/chest_xray/test"
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(180, 180),
    batch_size=1,
    class_mode='binary',
    shuffle=False
)
model = keras.models.load_model("/kaggle/input/best_vgg16_model/keras/default/1/best_vgg16_model.h5")
filenames = test_generator.filenames
class_labels = {v: k for k, v in test_generator.class_indices.items()}
num_images = len(filenames)
random_indices = random.sample(range(num_images), min(8, num_images))  # Changed to 8
fig, axes = plt.subplots(2, 4, figsize=(16, 8))  # Changed to 2x4 grid
print("\nPredictions for 8 Random Images:")

predictions = []  # List to store prediction results (True/False)
for i, ax in zip(random_indices, axes.flatten()):
    img_path = os.path.join(test_dir, filenames[i])
    img = keras.preprocessing.image.load_img(img_path, target_size=(180, 180))
    img_array = keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    pred = model.predict(img_array, verbose=0)[0][0]
    predicted_label = "PNEUMONIA" if pred > 0.5 else "NORMAL"
    original_class_index = test_generator.classes[i]
    original_label = class_labels[original_class_index]
    ax.imshow(img)
    ax.set_title(f"Pred: {predicted_label} ({pred:.2f})\nActual: {original_label}", fontsize=8)
    ax.axis('off')

    # Store prediction result
    predictions.append(predicted_label == original_label)

plt.tight_layout()
plt.show()

# --- Visualization of True vs. False Predictions ---
true_count = sum(predictions)
false_count = len(predictions) - true_count

plt.figure(figsize=(6, 6))
plt.bar(['True', 'False'], [true_count, false_count], color=['green', 'red'])
plt.ylabel('Number of Predictions')
plt.title('True vs. False Predictions (8 Random Images)')
plt.show()

"""Pass the img path to predict:"""

def predict_pneumonia(image_path, model_path="/kaggle/input/best_vgg16_model/keras/default/1/best_vgg16_model.h5"):
    model = keras.models.load_model(model_path)
    img = keras.preprocessing.image.load_img(image_path, target_size=(180, 180))
    img_array = keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array / 255.0
    pred = model.predict(img_array, verbose=0)[0][0]
    predicted_label = "PNEUMONIA" if pred > 0.5 else "NORMAL"
    plt.figure(figsize=(8, 8))
    plt.imshow(img)
    plt.title(f"Predicted Label: {predicted_label} (Probability: {pred:.2f})", fontsize=12)
    plt.axis('off')
    plt.show()

if __name__ == '__main__':
    image_path = input("Enter the path to your chest X-ray image: ")
    if not os.path.exists(image_path):
        print(f"Error: Image not found at {image_path}")
    else:
        predict_pneumonia(image_path)